In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../../3 - Cleaning & Transforming Data/1 cleaned_dataset_splited_output_NOALLELE_NODRUGDESC.csv', index_col = None)
df.drop(columns=['index','Cohort ethnicity','ADR','Pat1','ExpCtrl2'],inplace = True)

In [3]:
df_alleles_onehot = pd.get_dummies(df['Allele'], prefix = 'Allele', drop_first = True)

In [4]:
df = pd.concat([df, df_alleles_onehot], axis = 1)
df.drop(columns=['Allele'])
df_drug = pd.read_csv('../../1 - Drugs Descriptors/drug_descriptors_dataset.csv', index_col = None)

In [5]:
df = pd.merge(df, df_drug, left_on='Drug',right_on='DRUG_NAME', how='inner')

In [6]:
df.drop(columns=['Drug','DRUG_NAME','Allele'],inplace = True)

In [7]:
no_adr = df['No_ADR']
df.drop(columns=['No_ADR'], inplace = True)
df = pd.concat([no_adr,df], axis = 1)

In [8]:
df.iloc[:,0:9].sum(axis=1).sum() == len(df)

True

In [9]:
df['ADR_SJSI'] = df[['ADR_SJSI','ADR_SJSII']].sum(axis=1)
df.drop(['ADR_SJSII'], axis=1, inplace=True)
df.rename(columns={'ADR_SJSI':'ADR_SJS'}, inplace=True)
df

,No_ADR,ADR_AIU,ADR_Agranulocytosis,ADR_FDE,ADR_MPeruption,ADR_MPexanthema,ADR_SJS,ADR_TEN,Cohort ethnicity_Black,Cohort ethnicity_Caucasian,...,fr_sulfide,fr_sulfonamd,fr_sulfone,fr_term_acetylene,fr_tetrazole,fr_thiazole,fr_thiocyan,fr_thiophene,fr_unbrch_alkane,fr_urea
0,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
1,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
2,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
3,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
4,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17855,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
17856,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
17857,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
17858,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
17859,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [10]:
df.drop(columns=['ADR_Agranulocytosis','ADR_FDE','ADR_AIU'], inplace=True)
adr = pd.DataFrame(columns=['ADR'])
df

,No_ADR,ADR_MPeruption,ADR_MPexanthema,ADR_SJS,ADR_TEN,Cohort ethnicity_Black,Cohort ethnicity_Caucasian,Cohort ethnicity_Diverse,Cohort ethnicity_Mongol,Allele_A*01:01,...,fr_sulfide,fr_sulfonamd,fr_sulfone,fr_term_acetylene,fr_tetrazole,fr_thiazole,fr_thiocyan,fr_thiophene,fr_unbrch_alkane,fr_urea
0,0,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
1,0,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
2,0,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
3,0,0,0,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
4,0,0,0,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17855,1,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
17856,1,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
17857,1,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
17858,1,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
17859,1,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1

In [11]:
adr['ADR'] = df.iloc[:,1:5].sum(axis=1)
df = pd.concat([adr,df], axis = 1)
df

,ADR,No_ADR,ADR_MPeruption,ADR_MPexanthema,ADR_SJS,ADR_TEN,Cohort ethnicity_Black,Cohort ethnicity_Caucasian,Cohort ethnicity_Diverse,Cohort ethnicity_Mongol,...,fr_sulfide,fr_sulfonamd,fr_sulfone,fr_term_acetylene,fr_tetrazole,fr_thiazole,fr_thiocyan,fr_thiophene,fr_unbrch_alkane,fr_urea
0,1,0,0,0,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
1,1,0,0,0,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
2,1,0,0,0,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
3,1,0,0,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
4,1,0,0,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17855,0,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
17856,0,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
17857,0,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
17858,0,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
17859,0,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1

In [12]:
df[['ADR','No_ADR']].sum(axis=1).sum() == len(df)

False

In [13]:
df = df[df[['ADR','No_ADR']].sum(axis=1) == 1]

In [14]:
df[['ADR','No_ADR']].sum(axis=1).sum() == len(df)

True

In [15]:
df.drop(columns=['No_ADR','ADR_MPeruption','ADR_MPexanthema','ADR_SJS','ADR_TEN'], inplace=True)
df

c:\Users\harit\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\frame.py:4913: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

,ADR,Cohort ethnicity_Black,Cohort ethnicity_Caucasian,Cohort ethnicity_Diverse,Cohort ethnicity_Mongol,Allele_A*01:01,Allele_A*02,Allele_A*02:01,Allele_A*02:03,Allele_A*02:06,...,fr_sulfide,fr_sulfonamd,fr_sulfone,fr_term_acetylene,fr_tetrazole,fr_thiazole,fr_thiocyan,fr_thiophene,fr_unbrch_alkane,fr_urea
0,1,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,1,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,1,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,1,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,1,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17855,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
17856,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
17857,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
17858,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
17859,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [16]:
df.to_csv('cleaned_dataset_YESNOADR_noseq_drugdesc.csv',index=False)